name: opentad
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - aom=3.9.1
  - attr=2.5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cairo=1.18.4
  - certifi=2025.7.14
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=11.2.1
  - icu=75.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - level-zero=1.23.1
  - libabseil=20250127.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.3
  - libcap=2.75
  - libdeflate=1.24
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenvino=2025.0.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.50
  - libprotobuf=5.29.3
  - librsvg=2.58.4
  - libsndfile=1.2.2
  - libsqlite=3.45.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.7
  - libtiff=4.7.0
  - libudev1=257.7
  - libunwind=1.8.2
  - liburing=2.11
  - libusb=1.0.29
  - libuuid=2.38.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - mpg123=1.32.9
  - ncurses=6.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.6.0
  - openssl=3.5.1
  - pango=1.56.4
  - pcre2=10.45
  - pip=25.1
  - pixman=0.46.2
  - pthread-stubs=0.3
  - pugixml=1.15
  - pulseaudio-client=17.0
  - python=3.10.13
  - readline=8.2
  - sdl2=2.32.54
  - sdl3=3.2.18
  - snappy=1.2.1
  - sqlite=3.45.2
  - svt-av1=3.0.2
  - tbb=2022.1.0
  - tk=8.6.13
  - wayland=1.24.0
  - wayland-protocols=1.45
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - afsd==1.0
      - align1d==2.5.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - av==14.4.0
      - beautifulsoup4==4.13.4
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==45.0.4
      - cycler==0.12.1
      - decord==0.6.0
      - dinov2==0.0.1.dev0
      - einops==0.8.1
      - filelock==3.14.0
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - fvcore==0.1.5.post20221221
      - gdown==5.1.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hf-xet==1.1.5
      - huggingface-hub==0.33.0
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.37.0
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - jmespath==0.10.0
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mmaction2==1.2.0
      - mmcv==2.1.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nms-1d-cpu==0.0.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.18.0
      - onnxruntime==1.22.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.0
      - parameterized==0.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - portalocker==3.2.0
      - protobuf==6.31.1
      - psutil==7.0.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytorchvideo==0.1.5
      - pytz==2023.4
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.5.3
      - scikit-image==0.24.0
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - setuptools==60.2.0
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.1.0
      - tifffile==2025.5.10
      - timm==0.4.12
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchcodec==0.1.0+cu124
      - torchvision==0.17.2
      - tqdm==4.65.2
      - transformers==4.53.2
      - triton==2.2.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==1.26.20
      - wandb==0.20.1
      - yacs==0.1.8
      - yapf==0.43.0
      - zipp==3.23.0
prefix: /root/miniconda3/envs/opentad
